CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_BT_CTLR_TX_PWR_MINUS_8=y

CONFIG_ZMK_DISPLAY=n

# Pointing & Trackpoint Settings
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_INPUT_ACCELERATOR_LOG_ENABLED=y
CONFIG_CBPRINTF_COMPLETE=y

# Experimental BLE settings to improve performance on BT for mouse movement
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_THREAD_PRIORITY=3
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=8
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=8

# Logging
CONFIG_ZMK_LOGGING_MINIMAL=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000

# Stack sizes
CONFIG_THREAD_STACK_INFO=y
CONFIG_INIT_STACKS=y